import {
  Table,
  DollarSign,
  Hash,
  Calendar,
  SquareStack,
  ChevronDown,
  List,
  Type,
  Lock,
  AlignLeft,
  CheckSquare,
  Circle,
  Upload,
  Smartphone,
  Monitor,
  Play,
  Zap,
  Package,
  Database,
  Copy,
  Timer,
  RefreshCw,
  Keyboard,
} from "lucide-react"

export const components = [
  { title: "DataTable", url: "/docs/data-table", icon: Table, description: "Powerful data table with sorting and pagination", category: "Data & Display" },
  { title: "InputAmount", url: "/docs/input-amount", icon: DollarSign, description: "Specialized input for monetary amounts", category: "Advanced Inputs" },
  { title: "OtpInput", url: "/docs/otp-input", icon: Hash, description: "One-time password input with multiple fields", category: "Advanced Inputs" },
  { title: "DateRangePicker", url: "/docs/date-range-picker", icon: Calendar, description: "Date range picker with presets", category: "Advanced Inputs" },
  { title: "Modal", url: "/docs/modal", icon: SquareStack, description: "Flexible modal component with customizable sizing", category: "Overlays & Modals" },
  { title: "Dropdown", url: "/docs/dropdown", icon: ChevronDown, description: "Searchable dropdown with Command and Popover", category: "Layout & Navigation" },
  { title: "InputSelect", url: "/docs/input-select", icon: List, description: "Type-safe select input with labels and validation", category: "Layout & Navigation" },
  { title: "SelectDropdown", url: "/docs/select-dropdown", icon: ChevronDown, description: "Custom dropdown with keyboard navigation", category: "Layout & Navigation" },
  { title: "Input", url: "/docs/input", icon: Type, description: "Basic text input field", category: "Form Controls" },
  { title: "Password Input", url: "/docs/password-input", icon: Lock, description: "Password input with toggle", category: "Form Controls" },
  { title: "Textarea", url: "/docs/textarea", icon: AlignLeft, description: "Multi-line text input", category: "Form Controls" },
  { title: "Select", url: "/docs/select", icon: ChevronDown, description: "Dropdown select component", category: "Form Controls" },
  { title: "Checkbox", url: "/docs/checkbox", icon: CheckSquare, description: "Checkbox with label", category: "Form Controls" },
  { title: "Radio Group", url: "/docs/radio-group", icon: Circle, description: "Radio button group", category: "Form Controls" },
  { title: "File Input", url: "/docs/file-input", icon: Upload, description: "File upload component", category: "Form Controls" },
] as const

export const hooks = [
  { title: "useMobile", url: "/docs/hooks/use-mobile", icon: Smartphone, description: "Responsive viewport detection with SSR support", category: "Device & Layout" },
  { title: "useOnWindowResize", url: "/docs/hooks/useOnWindowResize", icon: Monitor, description: "Window resize event handling", category: "Device & Layout" },
  { title: "useOnMountEffect", url: "/docs/hooks/useOnMountEffect", icon: Play, description: "Mount-only effect execution", category: "Life Cycles" },
  { title: "useOnMountLayoutEffect", url: "/docs/hooks/useOnMountLayoutEffect", icon: Zap, description: "Mount-only layout effect with synchronous execution", category: "Life Cycles" },
  { title: "useOnUnmountEffect", url: "/docs/hooks/useOnUnmountEffect", icon: Package, description: "Cleanup logic that runs only on unmount", category: "Life Cycles" },
  { title: "useStateChangeEffect", url: "/docs/hooks/useStateChangeEffect", icon: Zap, description: "Effect triggered by state changes", category: "Life Cycles" },
  { title: "useIsomorphicLayoutEffect", url: "/docs/hooks/useIsomorphicLayoutEffect", icon: Monitor, description: "SSR-safe layout effects for universal apps", category: "Life Cycles" },
  { title: "useLocalStorage", url: "/docs/hooks/useLocalStorage", icon: Database, description: "Persistent localStorage state management", category: "State Management" },
  { title: "useCopyToClipboard", url: "/docs/hooks/use-copy-to-clipboard", icon: Copy, description: "Advanced clipboard operations", category: "Utilities" },
  { title: "useCountdown", url: "/docs/hooks/useCountdown", icon: Timer, description: "Countdown timers with loop support", category: "Utilities" },
  { title: "useRevalidate", url: "/docs/hooks/useRevalidate", icon: RefreshCw, description: "SWR cache revalidation helper", category: "Utilities" },
  { title: "useKeyboardShortcut", url: "/docs/hooks/useKeyboardShortcut", icon: Keyboard, description: "Global keyboard shortcuts with tooltip system", category: "Utilities" },
] as const
